port: 8080
# useHttps: true
# certFile: "certs/cert.pem"
# keyFile: "certs/key.pem"

routers:
  - host: iamfoo.localhost:8080
    service: whoami
  - host: testing.localhost:8080
    service: whoami
  - host: sreeram.localhost:8080
    service: whoami

services:
  - name: whoami
    url: "http://localhost:9000"